networks:
  iref-net:
    name: iref-network
    driver: bridge

volumes:
  minio_data:
    name: iref-minio-data
  pg_data:
    name: iref-pg-data
  pgadmin_data:
    name: iref-pgadmin-data

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: iref-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 10
      start_period: 20s
    
    networks:
       - iref-net 

  minio-setup:
    image: quay.io/minio/mc:latest
    container_name: iref-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://iref-minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb local/warehouse --ignore-existing;
      /usr/bin/mc mb local/bronze --ignore-existing;
      /usr/bin/mc mb local/silver --ignore-existing;
      /usr/bin/mc mb local/gold --ignore-existing;
      exit 0;
      "
    networks:
     - iref-net

  postgres:
    image: postgres:15-alpine
    container_name: iref-postgres
    environment:
      POSTGRES_USER: nessie
      POSTGRES_PASSWORD: nessie123
      POSTGRES_DB: nessie
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nessie"]
      interval: 5s
      retries: 5
    networks:
     - iref-net


  nessie:
    image: projectnessie/nessie:latest
    container_name: iref-nessie
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/nessie
      QUARKUS_DATASOURCE_USERNAME: nessie
      QUARKUS_DATASOURCE_PASSWORD: nessie123
      QUARKUS_HTTP_PORT: 19120
    ports:
      - "19120:19120"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19120/api/v2/config"]
      interval: 10s
      retries: 15
    networks:
     - iref-net

  spark-master:
    image: apache/spark:3.5.1
    container_name: iref-spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    depends_on:
      nessie:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    networks:
       - iref-net


  spark-worker:
    image: apache/spark:3.5.1
    container_name: iref-spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker spark://spark-master:7077 -c spark.worker.memory=2g -c spark.worker.cores=2
    depends_on:
      - spark-master
    environment:
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_CORES: 2
    networks:
     - iref-net

  trino:
    image: trinodb/trino:476
    container_name: iref-trino
    ports:
      - "8081:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    depends_on:
      nessie:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/v1/info || exit 1"]
      interval: 15s
      retries: 10
    networks:
       - iref-net
